//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brigadier.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BrigadierEntities : DbContext
    {
        public BrigadierEntities()
            : base("name=BrigadierEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<History> Histories { get; set; }
        public virtual IDbSet<LinkType> LinkTypes { get; set; }
        public virtual IDbSet<Thread> Threads { get; set; }
        public virtual IDbSet<WatchedSub> WatchedSubs { get; set; }
    }
}
