//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brigadier.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public int ThreadId { get; set; }
        public System.DateTime Time { get; set; }
        public int Score { get; set; }
    
        public virtual Thread Thread { get; set; }
    }
}
