CREATE TABLE [dbo].[Thread]
(
	[Id] INT IDENTITY(1,1) NOT NULL, 
    [Url] NVARCHAR(MAX) NOT NULL, 
    [Author] NVARCHAR(25) NOT NULL, 
	[Sub] NVARCHAR(25) NOT NULL,
    CONSTRAINT [PK_dbo.Thread] PRIMARY KEY CLUSTERED ([Id] ASC),
)
